version: '3.3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: products
      # User`s data for access to db
      MYSQL_USER: rest
      MYSQL_PASSWORD: secret
      # Password for root access
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  web:
    restart: always
    container_name: flask-python
    build: .
    ports:
      - "80:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    volumes:
      - ./:/usr/src/api/

# Names our volume
volumes:
  my-db:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1